services:
  database:
    image: postgres:15-alpine
    container_name: banco_postgres
    environment:
      - POSTGRES_USER=bank
      - POSTGRES_PASSWORD=bank
      - POSTGRES_DB=bank
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workout -d workout"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_banco
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database