"""initial_structure

Revision ID: 8a3a326cd7d4
Revises:
Create Date: 2026-01-03 19:49:38.846294

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.schema import CreateSequence, DropSequence
from sqlalchemy.schema import Sequence as Seq

# revision identifiers, used by Alembic.
revision: str = "8a3a326cd7d4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Seq("account_number_seq", start=10001, increment=1)))
    op.create_table(
        "users",
        sa.Column("pk_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=60), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("pk_id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "accounts",
        sa.Column("pk_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("branch", sa.String(length=4), nullable=False),
        sa.Column("account_number", sa.String(length=20), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column(
            "daily_withdrawal_limit",
            sa.DECIMAL(precision=12, scale=2),
            nullable=False,
            comment="Maximum cumulative withdrawal amount allowed per day.",
        ),
        sa.Column(
            "transfer_limit",
            sa.DECIMAL(precision=12, scale=2),
            nullable=False,
            comment="Maximum amount allowed per transfer.",
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.pk_id"],
        ),
        sa.PrimaryKeyConstraint("pk_id"),
        sa.UniqueConstraint("account_number"),
    )
    op.create_table(
        "transactions",
        sa.Column("pk_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column(
            "type",
            sa.Enum("DEPOSIT", "WITHDRAWAL", "TRANSFER_IN", "TRANSFER_OUT", name="transactiontype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("counterparty_name", sa.String(length=60), nullable=True),
        sa.Column("counterparty_branch", sa.String(length=4), nullable=True),
        sa.Column("counterparty_account_number", sa.String(length=20), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.pk_id"],
        ),
        sa.PrimaryKeyConstraint("pk_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("accounts")
    op.drop_table("users")
    op.execute(DropSequence(Seq("account_number_seq")))
    # ### end Alembic commands ###
