"""add_operation_id_on_transaction

Revision ID: bda0afade2df
Revises: 4354b4c6a84b
Create Date: 2026-01-15 17:47:25.675417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda0afade2df'
down_revision: Union[str, Sequence[str], None] = '4354b4c6a84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('operation_id', sa.UUID(), nullable=True))
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_operation_id'), 'transactions', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_operation_id'), table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_column('transactions', 'operation_id')
    # ### end Alembic commands ###
